/* WARNING: Do not edit this file "tupl_impl.hpp"
   =======
* it's generated by preprocessing "tupl_impl.pp" so is overwritten
* each time the preprocessing step is rerun, very likely automatically.
***********************************************************************/
