/* WARNING: Do not edit this file "tupl_impl.hpp"
   =======
* it's generated by preprocessing "tupl_impl_pre.hpp" so is overwritten
* each time the preprocessing step is rerun, preferably automatically.
***********************************************************************/
/*
     Copyright (c) 2021 Will Wray https://keybase.io/willwray

     Distributed under the Boost Software License, Version 1.0.
           http://www.boost.org/LICENSE_1_0.txt

     Repo: https://github.com/willwray/tupl
*/